### ISSUE TITLE
Docs: More information into "Opting into `#[may_dangle]` and the `dropck_eyepatch`" section of `MaybeDangling`

### ISSUE THREAD

**Issue by jofas** [danielhenrymantilla/maybe-dangling.rs#3]
[This](https://docs.rs/maybe-dangling/latest/maybe_dangling/struct.MaybeDangling.html#opting-into-may_dangle-and-the-dropck_eyepatch) section of the documentation seems a little sparse to me (someone not familiar with dropck and its subtleties). I'd like to add these links to the text:

* [The nomicon section](https://doc.rust-lang.org/nomicon/dropck.html)
* [The section from `std::ops::Drop`](https://doc.rust-lang.org/std/ops/trait.Drop.html#drop-check)
* [The `dropck_eyepatch` RFC](https://doc.rust-lang.org/std/ops/trait.Drop.html#drop-check)

and maybe add a sentence along the lines of: 

> Even though the `Drop` implementation of `MaybeDangling` does not access any potentially dangling pointers stored inside, without `#[may_dangle]` dropck will still fail compilation, since it doesn't know the internal implementation of `Drop`.

I was also contemplating adding an example, though this might be too much. Also I couldn't come up with a better one than replacing `Inspector` with `MaybeDangling` from the nomicon example.

Thoughts?

**Comment by danielhenrymantilla** [comment]
@jofas yeah I admit I was quite laconic in that section, so improving this to make it more user-friendly would be great! Also mentioning [this other nomicon section](https://doc.rust-lang.org/nomicon/phantom-data.html#generic-parameters-and-drop-checking) would be useful. If you have the time then it would be nice for you to submit a PR with the doc improvements, and then I'll probably make rewording suggestions there, that way we should end up with a text fitting two Rust programmer profiles 🙂
